### ISSUE TITLE
Page body disappears after 'refactor the add tip action creator function to be a thunk action'.

### ISSUE THREAD

**Issue by bazzaar** [croservices/sample-app-spa-react#2]
Hi, 
***UPDATE***

To be clear, this issue is about the "Building a Single Page Application with Cro" web tutorial, not about the code (per se) in this repository. The code section in the tutorial web page that documents the initial creation of the 'frontend/reducer.js' file appears to me to contain a coding glitch (on line 332 when viewing the page source in Firefox). The code glitch is simple to fix (see details below). For a user who is following the tutorial and cutting/pasting the code segments from the web page to build the application files, the code glitch results in a confusing situation where the 'div' section containing the application UI disappears from the web page in the browser. Eventually the cumulative changes made to 'frontend/reducer.js' as the tutorial proceeds, corrects the situation ... but before arriving at that point the user may a) have wasted time trying to start the tutorial again, and then finding the problem didn't go away tried to find other likely reasons for the issue, or b) simply given up.

In the WEB TUTORIAL,

I think I've tracked the problem down ...

it's in the initialisation of frontend/reducer.js    <<<<< not the file, the web page section

.... the web page code section initialises the file with ...        

import ActionTypes from './actions';

... this needs needs to be replaced in the web page by ..

import * as ActionTypes from './actions';

*** UPDATE end ***

I've hit the same snag a couple of times now re-following the tutorial, the text says 'Note that this doesn't yet change anything; build it and the behavior should be just the same.' -- but it isn't the same, after an 'npm run build' the page body (div section containing the app) disappears, and doesn't reappear (at least as far as adding the ajax post to the backend). Only now am I contemplating proceeding further into the tutorial, to see if it reappears eventually. I thought for a while it may have been my npm setup ( checking into reason for fsevents warnings, etc.).

Just to be sure, I installed the complete app by cloning it, and that works ok. So that's why I'm feeling confident enough to post this as an issue (maybe just a bit of explanatory text is sufficient?).

Brilliant tutorial by the way, probably me being stupid, if so please forgive...

bazzaar

**Comment by bazzaar** [comment]
Also please note there is an unrelated typo on line 466 in the tutorial web page..

'frontend/reducers.js' should be 'frontend/reducer.js'

**Comment by japhb** [comment]
I saw this myself, bazzaar's 5-character fix made it work immediately (well, OK, after `npm run build`).

**Comment by jnthn** [comment]
@bazzaar Thanks very much for taking the time to track down what the problem was. I just committed the two fixes in https://github.com/croservices/cro/commit/878b5d5e017cf2099f3d75c7a81ee99c0d373e96, and they will be updated next time the website is deployed.
